<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ExcelLogin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b233ea24-5414-4115-a182-148cd1f55cae</testSuiteGuid>
   <testCaseLink>
      <guid>ddd2b263-9f8a-4409-a623-9daad155e724</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DTCM/Login and logout/DataExtractingFromExcel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d5b02fbc-91b6-4607-9ae0-7b6982380516</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d5b02fbc-91b6-4607-9ae0-7b6982380516</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c0a6ad0b-262f-4d39-94bb-fa61ffb6a3b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d5b02fbc-91b6-4607-9ae0-7b6982380516</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>208976fb-b045-428c-8aa1-8e6e14ec158d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
