<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubmitButtonPromoSC</name>
   <tag></tag>
   <elementGuidId>cc4c6e41-12cb-4520-a5ac-5a28cfe0b78d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.scButtonPrimary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.scButtonPrimary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Iframe2SC</value>
   </webElementProperties>
</WebElementEntity>
