<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubmitBtnVariantSC</name>
   <tag></tag>
   <elementGuidId>8dbea43c-dcbf-4f2a-a712-5dbc8b20645c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.scButton.scButtonPrimary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.scButton.scButtonPrimary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Iframe2SC</value>
   </webElementProperties>
</WebElementEntity>
