<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VariantSelectionSC</name>
   <tag></tag>
   <elementGuidId>e8fac993-db66-4d38-8773-e07405a9ccc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.scContentControl.scCombobox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.scContentControl.scCombobox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Iframe2SC</value>
   </webElementProperties>
</WebElementEntity>
